"""add_import_mode_and_cutoff_to_pathful_import_log

Revision ID: 19c9840f1b3c
Revises: db30c611d449
Create Date: 2026-04-13 09:04:36.461708

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19c9840f1b3c"
down_revision: Union[str, Sequence[str], None] = "db30c611d449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pathful_import_log", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("import_mode", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column("cutoff_date", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("skipped_historic_rows", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pathful_import_log", schema=None) as batch_op:
        batch_op.drop_column("skipped_historic_rows")
        batch_op.drop_column("cutoff_date")
        batch_op.drop_column("import_mode")

    # ### end Alembic commands ###
