"""add_provenance_fields_to_event_attendance_detail

Revision ID: 3ad6f506531f
Revises: c684248d354a
Create Date: 2026-05-04 11:22:27.816091

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ad6f506531f"
down_revision: Union[str, Sequence[str], None] = "c684248d354a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_attendance_detail", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("data_source", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_updated_by", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_event_attendance_detail_last_updated_by_users",
            "users",
            ["last_updated_by"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_attendance_detail", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_event_attendance_detail_last_updated_by_users", type_="foreignkey"
        )
        batch_op.drop_column("last_updated_by")
        batch_op.drop_column("notes")
        batch_op.drop_column("last_verified_at")
        batch_op.drop_column("data_source")

    # ### end Alembic commands ###
