"""Add district_name to GoogleSheet

Revision ID: 80188e1a37e7
Revises: f8dd4c0aacea
Create Date: 2026-01-25 18:24:40.784996

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80188e1a37e7"
down_revision: Union[str, Sequence[str], None] = "f8dd4c0aacea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("google_sheets", schema=None) as batch_op:
        pass
        # batch_op.add_column(sa.Column('district_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table("teacher_progress", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_teacher_progress_last_import_id",
            "roster_import_log",
            ["last_import_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_teacher_progress_teacher_id", "teacher", ["teacher_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teacher_progress", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("google_sheets", schema=None) as batch_op:
        batch_op.drop_column("district_name")

    # ### end Alembic commands ###
