"""Add severity and source to DataQualityFlag

Revision ID: 94834b169ed7
Revises: 334af5895d87
Create Date: 2026-04-29 11:26:56.317722

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94834b169ed7"
down_revision: Union[str, Sequence[str], None] = "334af5895d87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: migration 334af5895d87 (which runs before this one in the chain) already:
    #   - renamed all ix_dqf_* indexes to ix_data_quality_flag_* names
    #   - created ix_data_quality_flag_entity_sf_id
    #   - created uix_dqf_entity_issue (including entity_sf_id in the constraint)
    # So this migration only adds severity/source columns + their indexes.
    with op.batch_alter_table("data_quality_flag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "severity",
                sa.String(length=20),
                nullable=False,
                server_default="warning",
            )
        )
        batch_op.add_column(
            sa.Column(
                "source", sa.String(length=50), nullable=False, server_default="unknown"
            )
        )
        batch_op.create_index(
            batch_op.f("ix_data_quality_flag_severity"), ["severity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_quality_flag_source"), ["source"], unique=False
        )

    with op.batch_alter_table("email_delivery_attempts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("provider_message_id", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("provider_response", sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_email_delivery_attempts_mailjet_message_id"))
        batch_op.create_index(
            batch_op.f("ix_email_delivery_attempts_provider_message_id"),
            ["provider_message_id"],
            unique=False,
        )
        batch_op.drop_column("mailjet_message_id")
        batch_op.drop_column("mailjet_response")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_delivery_attempts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mailjet_response", sqlite.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("mailjet_message_id", sa.VARCHAR(length=100), nullable=True)
        )
        batch_op.drop_index(
            batch_op.f("ix_email_delivery_attempts_provider_message_id")
        )
        batch_op.create_index(
            batch_op.f("ix_email_delivery_attempts_mailjet_message_id"),
            ["mailjet_message_id"],
            unique=False,
        )
        batch_op.drop_column("provider_response")
        batch_op.drop_column("provider_message_id")

    with op.batch_alter_table("data_quality_flag", schema=None) as batch_op:
        batch_op.drop_constraint("uix_dqf_entity_issue", type_="unique")
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_status"))
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_source"))
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_severity"))
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_salesforce_id"))
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_issue_type"))
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_entity_type"))
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_entity_sf_id"))
        batch_op.drop_index(batch_op.f("ix_data_quality_flag_entity_id"))
        batch_op.create_index(batch_op.f("ix_dqf_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dqf_salesforce_id"), ["salesforce_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dqf_issue_type"), ["issue_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dqf_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dqf_entity_id"), ["entity_id"], unique=False
        )
        batch_op.drop_column("source")
        batch_op.drop_column("severity")

    # ### end Alembic commands ###
