"""teacher_deactivation_provenance

Revision ID: 9c2ca740117a
Revises: 9af4536e98fa
Create Date: 2026-05-05 12:21:48.753613

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c2ca740117a"
down_revision: Union[str, Sequence[str], None] = "9af4536e98fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roster_import_log", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "records_flagged", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(sa.Column("flagged_details", sa.Text(), nullable=True))

    with op.batch_alter_table("teacher_progress", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "deactivation_source",
                sa.Enum(
                    "IMPORT_DIFF",
                    "MANUAL_ADMIN",
                    "YEAR_END",
                    "PURGE",
                    name="deactivationsource",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("deactivated_by", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("deactivation_reason", sa.String(length=200), nullable=True)
        )
        batch_op.add_column(
            sa.Column("deactivation_notes", sa.String(length=500), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_teacher_progress_deactivated_by_users",
            "users",
            ["deactivated_by"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teacher_progress", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_teacher_progress_deactivated_by_users", type_="foreignkey"
        )
        batch_op.drop_column("deactivation_notes")
        batch_op.drop_column("deactivation_reason")
        batch_op.drop_column("deactivated_at")
        batch_op.drop_column("deactivated_by")
        batch_op.drop_column("deactivation_source")

    with op.batch_alter_table("roster_import_log", schema=None) as batch_op:
        batch_op.drop_column("flagged_details")
        batch_op.drop_column("records_flagged")

    # ### end Alembic commands ###
