"""add_alias_models

Revision ID: b905e23c42aa
Revises: a1b2c3_fix_drifts
Create Date: 2026-03-30 19:53:16.683036

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b905e23c42aa"
down_revision: Union[str, Sequence[str], None] = "a1b2c3_fix_drifts"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "is_auto_generated", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organization_alias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_alias_name"), ["name"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_organization_alias_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "school_alias",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("school_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("school_alias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_school_alias_alias"), ["alias"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_school_alias_school_id"), ["school_id"], unique=False
        )

    with op.batch_alter_table("connector_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connector_data_active_subscription"))

    op.drop_table("connector_data")
    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=200),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    op.create_table(
        "connector_data",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("volunteer_id", sa.INTEGER(), nullable=False),
        sa.Column("user_auth_id", sa.VARCHAR(length=7), nullable=True),
        sa.Column("joining_date", sa.VARCHAR(length=50), nullable=True),
        sa.Column("last_login_datetime", sa.VARCHAR(length=50), nullable=True),
        sa.Column("last_update_date", sa.DATE(), nullable=True),
        sa.Column("active_subscription", sa.VARCHAR(length=8), nullable=True),
        sa.Column("active_subscription_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("role", sa.VARCHAR(length=20), nullable=True),
        sa.Column("signup_role", sa.VARCHAR(length=20), nullable=True),
        sa.Column("profile_link", sa.VARCHAR(length=1300), nullable=True),
        sa.Column("affiliations", sa.TEXT(), nullable=True),
        sa.Column("industry", sa.VARCHAR(length=255), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["volunteer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_auth_id", name=op.f("uix_connector_user_auth_id")),
        sa.UniqueConstraint("volunteer_id", name=op.f("uix_connector_volunteer_id")),
    )
    with op.batch_alter_table("connector_data", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_connector_data_active_subscription"),
            ["active_subscription"],
            unique=False,
        )

    with op.batch_alter_table("school_alias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_school_alias_school_id"))
        batch_op.drop_index(batch_op.f("ix_school_alias_alias"))

    op.drop_table("school_alias")
    with op.batch_alter_table("organization_alias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_alias_organization_id"))
        batch_op.drop_index(batch_op.f("ix_organization_alias_name"))

    op.drop_table("organization_alias")
    # ### end Alembic commands ###
