"""drop dead district_engagement_reports table

Revision ID: c684248d354a
Revises: 94834b169ed7
Create Date: 2026-05-03 14:44:33.585386

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c684248d354a"
down_revision: Union[str, Sequence[str], None] = "94834b169ed7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("district_engagement_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_engagement_school_year_updated"))
        batch_op.drop_index(batch_op.f("ix_district_engagement_reports_school_year"))

    op.drop_table("district_engagement_reports")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "district_engagement_reports",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("district_id", sa.VARCHAR(length=18), nullable=False),
        sa.Column("school_year", sa.VARCHAR(length=4), nullable=False),
        sa.Column("summary_stats", sqlite.JSON(), nullable=False),
        sa.Column("volunteers_data", sqlite.JSON(), nullable=True),
        sa.Column("students_data", sqlite.JSON(), nullable=True),
        sa.Column("events_data", sqlite.JSON(), nullable=True),
        sa.Column("breakdown_data", sqlite.JSON(), nullable=True),
        sa.Column("last_updated", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["district.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "district_id",
            "school_year",
            name=op.f("uix_district_engagement_school_year"),
        ),
    )
    with op.batch_alter_table("district_engagement_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_district_engagement_reports_school_year"),
            ["school_year"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_engagement_school_year_updated"),
            ["school_year", "last_updated"],
            unique=False,
        )

    # ### end Alembic commands ###
