"""fix_organization_timestamps_for_sqlite

Revision ID: d9dd0eb34119
Revises: a1449af93a2e
Create Date: 2025-08-17 09:45:58.207497

"""

from datetime import datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d9dd0eb34119"
down_revision = "a1449af93a2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # For SQLite, we need to recreate the table to change column defaults
    # First, create a new table with the correct schema
    op.create_table(
        "organization_new",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("salesforce_id", sa.String(length=18), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("volunteer_salesforce_id", sa.String(length=18), nullable=True),
        sa.Column("billing_street", sa.String(length=255), nullable=True),
        sa.Column("billing_city", sa.String(length=255), nullable=True),
        sa.Column("billing_state", sa.String(length=255), nullable=True),
        sa.Column("billing_postal_code", sa.String(length=255), nullable=True),
        sa.Column("billing_country", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            default=datetime.utcnow,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            default=datetime.utcnow,
        ),
        sa.Column("last_activity_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Copy data from old table to new table
    op.execute(
        """
        INSERT INTO organization_new (
            id, salesforce_id, name, type, description, volunteer_salesforce_id,
            billing_street, billing_city, billing_state, billing_postal_code, billing_country,
            created_at, updated_at, last_activity_date
        )
        SELECT
            id, salesforce_id, name, type, description, volunteer_salesforce_id,
            billing_street, billing_city, billing_state, billing_postal_code, billing_country,
            COALESCE(created_at, datetime('now')) as created_at,
            COALESCE(updated_at, datetime('now')) as updated_at,
            last_activity_date
        FROM organization
    """
    )

    # Drop old table and rename new table
    op.drop_table("organization")
    op.rename_table("organization_new", "organization")

    # Recreate indexes
    op.create_index(
        op.f("ix_organization_salesforce_id"),
        "organization",
        ["salesforce_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_organization_name"), "organization", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_organization_volunteer_salesforce_id"),
        "organization",
        ["volunteer_salesforce_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert to the old schema if needed
    # Note: This is a destructive operation and will lose data
    pass

    # ### end Alembic commands ###
