"""Add queued_undated_count to PathfulImportLog

Revision ID: db30c611d449
Revises: b905e23c42aa
Create Date: 2026-04-10 12:06:21.912759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db30c611d449'
down_revision: Union[str, Sequence[str], None] = 'b905e23c42aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathful_import_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queued_undated_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathful_import_log', schema=None) as batch_op:
        batch_op.drop_column('queued_undated_count')

    # ### end Alembic commands ###
