"""TeacherProgress roster import updates

Revision ID: f8dd4c0aacea
Revises: a1b2c3d4e5f6
Create Date: 2026-01-25 17:10:10.321298

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8dd4c0aacea"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_contact_exclude_first_date'), table_name='contact')
    # op.drop_index(op.f('idx_contact_exclude_from_reports'), table_name='contact')
    # op.drop_index(op.f('idx_event_future_status'), table_name='event')
    # op.drop_index(op.f('idx_event_last_volunteer'), table_name='event')
    # op.drop_index(op.f('idx_event_start_date_status'), table_name='event')
    # op.drop_index(op.f('idx_event_participation_event_id'), table_name='event_participation')
    # op.drop_index(op.f('idx_event_participation_future'), table_name='event_participation')
    # op.drop_index(op.f('idx_event_participation_status'), table_name='event_participation')
    # op.drop_index(op.f('idx_event_participation_volunteer_id'), table_name='event_participation')
    # op.drop_index(op.f('idx_event_participation_volunteer_status'), table_name='event_participation')
    # op.drop_index(op.f('idx_volunteer_total_count'), table_name='event_participation')
    # op.add_column('teacher_progress', sa.Column('is_active', sa.Boolean(), nullable=False, server_default="1"))
    # op.add_column('teacher_progress', sa.Column('district_name', sa.String(length=200), nullable=True))
    # op.add_column('teacher_progress', sa.Column('last_import_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'teacher_progress', 'teacher', ['teacher_id'], ['id'])
    # op.create_foreign_key(None, 'teacher_progress', 'roster_import_log', ['last_import_id'], ['id'])
    op.drop_index(op.f("idx_volunteer_first_volunteer_date"), table_name="volunteer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_volunteer_first_volunteer_date"),
        "volunteer",
        ["first_volunteer_date"],
        unique=False,
    )
    op.drop_constraint(None, "teacher_progress", type_="foreignkey")
    op.drop_constraint(None, "teacher_progress", type_="foreignkey")
    op.drop_column("teacher_progress", "last_import_id")
    op.drop_column("teacher_progress", "district_name")
    op.drop_column("teacher_progress", "is_active")
    op.create_index(
        op.f("idx_volunteer_total_count"),
        "event_participation",
        ["volunteer_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_participation_volunteer_status"),
        "event_participation",
        ["volunteer_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_participation_volunteer_id"),
        "event_participation",
        ["volunteer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_participation_status"),
        "event_participation",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_participation_future"),
        "event_participation",
        ["volunteer_id", "event_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_participation_event_id"),
        "event_participation",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_start_date_status"),
        "event",
        ["start_date", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_last_volunteer"), "event", ["start_date", "id"], unique=False
    )
    op.create_index(
        op.f("idx_event_future_status"), "event", ["start_date", "status"], unique=False
    )
    op.create_index(
        op.f("idx_contact_exclude_from_reports"),
        "contact",
        ["exclude_from_reports"],
        unique=False,
    )
    op.create_index(
        op.f("idx_contact_exclude_first_date"),
        "contact",
        ["exclude_from_reports", "id"],
        unique=False,
    )
    # ### end Alembic commands ###
