#!/usr/bin/env python3
"""
Database Comparison Utility
===========================

Compares table schemas and row counts between two SQLite databases.
Tables are grouped into four tiers by importance:

  CRITICAL  — Manually managed data that cannot be regenerated from imports.
               Differences here need deliberate action (e.g. attendance_override,
               organization_alias, users).

  HIGH      — Core entity tables (volunteer, teacher, event, etc.).
               Diffs here may indicate real data loss or unsynced imports.

  MEDIUM    — Linkage and attribute tables (event_volunteers, volunteer_org, etc.).
               Diffs often follow naturally from CORE diffs.

  LOW       — Append-only logs, caches, and import bookkeeping.
               Diffs here are expected and usually ignorable.

Usage:
    python scripts/maintenance/compare_databases.py
    python scripts/maintenance/compare_databases.py instance/prod/your_database.db instance/your_database.db
    python scripts/maintenance/compare_databases.py --ignore-low
    python scripts/maintenance/compare_databases.py --all
"""

import argparse
import os
import sqlite3
import sys

# ── Table tier definitions ─────────────────────────────────────────────────────

# Data that is MANUALLY created and cannot be regenerated by re-running imports.
# A diff here always requires deliberate review.
CRITICAL_TABLES = [
    "attendance_override",  # Manual attendance corrections
    "organization_alias",  # Admin-confirmed org name mappings
    "district_alias",  # Admin-confirmed district name mappings
    "school_alias",  # Admin-confirmed school name mappings
    "teacher_data_flag",  # Manually flagged teacher data issues
    "event_flag",  # Manually flagged events
    "district_manual_inputs",  # Hand-entered district data
    "recruitment_note",  # Manually entered recruitment notes
    "outreach_attempt",  # Manually entered outreach records
    "users",  # Admin/staff user accounts
    "magic_link",  # Active session magic links
    "event_comment",  # Manually entered event comments
    "student",  # Student records (not from Pathful — from rosters)
    "google_sheets",  # Manually managed Google Sheets links
]

# Core entity tables that come from Salesforce/Pathful/roster imports.
# A large unexpected diff here may indicate a sync issue.
CORE_TABLES = [
    "volunteer",
    "teacher",
    "organization",
    "event",
    "contact",
    "school",
    "district",
    "class",
]

# Append-only logs, caches, and import bookkeeping — expected to drift naturally.
LOW_TABLES = [
    "audit_log",
    "sync_logs",
    "pathful_import_log",
    "pathful_unmatched_record",
    "roster_import_log",
    "bug_reports",
    "email_delivery_attempts",
    "email_messages",
    "validation_runs",
    "validation_history",
    "validation_results",
    "alembic_version",
    "data_quality_flag",
    "connector_data",
]


def get_table_info(db_path):
    """
    Returns ({table: row_count}, {table: [columns]}) for the given SQLite database.
    Returns (None, None) if the file cannot be opened.
    """
    if not os.path.exists(db_path):
        print(f"Error: Database file not found at '{db_path}'")
        return None, None

    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';"
        )
        tables = [row[0] for row in cursor.fetchall()]

        counts = {}
        columns = {}
        for table in tables:
            try:
                cursor.execute(f"SELECT COUNT(*) FROM {table}")
                counts[table] = cursor.fetchone()[0]
                cursor.execute(f"PRAGMA table_info({table})")
                columns[table] = [row[1] for row in cursor.fetchall()]
            except sqlite3.OperationalError:
                pass

        conn.close()
        return counts, columns
    except Exception as e:
        print(f"Error reading {db_path}: {e}")
        return None, None


def tier(table):
    if table in CRITICAL_TABLES:
        return "CRITICAL — Manually Managed (cannot be regenerated)"
    if table in CORE_TABLES:
        return "HIGH — Core Entities"
    if table in LOW_TABLES or "cache" in table:
        return "LOW — Logs, Caches & Import Bookkeeping"
    return "MEDIUM — Linkages & Attributes"


TIER_ORDER = [
    "CRITICAL — Manually Managed (cannot be regenerated)",
    "HIGH — Core Entities",
    "MEDIUM — Linkages & Attributes",
    "LOW — Logs, Caches & Import Bookkeeping",
]


def main():
    parser = argparse.ArgumentParser(
        description="Compare row counts between two SQLite databases",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "db1",
        nargs="?",
        default="instance/prod/your_database.db",
        help="Path to DB 1, default: instance/prod/your_database.db",
    )
    parser.add_argument(
        "db2",
        nargs="?",
        default="instance/your_database.db",
        help="Path to DB 2, default: instance/your_database.db",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Show all tables, even those with matching counts",
    )
    parser.add_argument(
        "--ignore-low",
        action="store_true",
        help="Hide LOW-tier tables (logs, caches) which drift naturally",
    )

    args = parser.parse_args()

    print(f"\nComparing Databases")
    print(f"  DB1 (prod): {args.db1}")
    print(f"  DB2 (local): {args.db2}")
    print("=" * 72)

    counts1, cols1 = get_table_info(args.db1)
    counts2, cols2 = get_table_info(args.db2)

    if counts1 is None or counts2 is None:
        sys.exit(1)

    all_tables = sorted(set(list(counts1.keys()) + list(counts2.keys())))

    # Build groups
    groups = {t: [] for t in TIER_ORDER}
    for table in all_tables:
        t = tier(table)
        c1 = counts1.get(table, 0)
        c2 = counts2.get(table, 0)
        diff = c1 - c2

        if args.ignore_low and t == "LOW — Logs, Caches & Import Bookkeeping":
            continue

        if diff != 0 or args.all:
            pct = f"({abs(diff) / c1 * 100:.1f}%)" if diff != 0 and c1 else ""
            only_in = ""
            if table not in counts1:
                only_in = "  ← only in DB2"
            elif table not in counts2:
                only_in = "  ← only in DB1"
            groups[t].append((table, c1, c2, diff, pct, only_in))

    # Print grouped output
    any_diff = False
    for tier_name in TIER_ORDER:
        rows = groups.get(tier_name, [])
        if not rows:
            continue
        any_diff = True
        print(f"\n[{tier_name}]")
        print(f"  {'Table':<38} {'DB1':>8} {'DB2':>8} {'Diff':>8}  {'Drift%':<9}")
        print(f"  {'-'*38} {'-'*8} {'-'*8} {'-'*8}  {'-'*9}")
        for table, c1, c2, diff, pct, only_in in rows:
            diff_str = f"{diff:+d}" if diff != 0 else ""
            print(f"  {table:<38} {c1:>8} {c2:>8} {diff_str:>8}  {pct:<9}{only_in}")

    if not any_diff:
        print("\n  ✓ No differences found across checked tables.")

    # Schema differences — tables only in one DB
    missing_db1 = [t for t in all_tables if t not in counts1]
    missing_db2 = [t for t in all_tables if t not in counts2]

    if missing_db1 or missing_db2:
        print(f"\n[SCHEMA — Tables present in only one database]")
        for t in missing_db1:
            print(f"  - '{t}' is in DB2 only  (tier: {tier(t)})")
        for t in missing_db2:
            print(f"  - '{t}' is in DB1 only  (tier: {tier(t)})")

    if not args.all and not args.ignore_low:
        print(
            "\nTip: run with --ignore-low to hide log/cache tables, or --all to show matching tables too."
        )
    print()


if __name__ == "__main__":
    main()
